In [113]:
from tqdm import tqdm_notebook as tqdm

In [114]:
import requests as req

200 : 성공

In [115]:
res = req.get('http://naver.com')
res

html을 text로 받아오기

requets라이브러리를 활용하여 melon사이트 데이터 요청하기
- 406오류 : 허가되지 않은 접근

In [116]:
res = req.get('https://www.melon.com/')
res

In [117]:
header = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'}

In [118]:
res = req.get("https://www.melon.com/", headers = header)

header의 속성에 변수를 선언해줌

In [119]:
res
# res.text

In [120]:
from bs4 import BeautifulSoup as bs

In [121]:
header = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'}
 
url = "https://www.melon.com/chart/index.htm"
res = req.get(url, headers=header).text
# get함수로 raw데이터 가져오기
soup = bs(res, "lxml")
# request로 가져온 데이터를 분석할 수 있게 객체화 시킴, 
# BeautifulSoup(html, 'html.parser') -> 해당 문자열의 종류 : html 등 , 파서의 종류 지정 : html.parser or lxml 

# < CSS selector를 통해 tag 객체를 찾아 반환, hrml.parser를 통해 객체화 선행 후 진행>
song_name = soup.select("#lst50 > td > div > div > div.ellipsis.rank01 > span > a")
artist_name = soup.select("#frm > div > table > tbody > tr > td > div > div > div.ellipsis.rank02 > a")
album_name = soup.select("#lst50 > td > div > div > div.ellipsis.rank03 > a")
# 태그를 찾아오는 명령어
# 특정tag의 하위tag를 " > "를 통해 명시함
# 특정tag와 class, 온점을 통해 태그와 클래스 이름 분리 ex) div.ellipsis.rank01

artist_name = soup.select("#frm > div > table > tbody > tr > td > div > div > div.ellipsis.rank02")
 
for i in range(len(artist_name)):
    artist_name[i] = artist_name[i].select("div > a")
    for j in range(len(artist_name[i])):
        artist_name[i][j] = artist_name[i][j].text

for i in range(len(song_name)):
    song_name[i] = song_name[i].text
    
for i in range(len(album_name)):
    album_name[i] = album_name[i].text
    
for i in range(len(album_name)):
    print(f'{i+1}위 {song_name[i]} / {artist_name[i]} / {album_name[i]}')

1위 After LIKE / ['IVE (아이브)'] / After LIKE
2위 Attention / ['NewJeans'] / NewJeans 1st EP 'New Jeans'
3위 Pink Venom / ['BLACKPINK'] / Pink Venom
4위 Hype boy / ['NewJeans'] / NewJeans 1st EP 'New Jeans'
5위 LOVE DIVE / ['IVE (아이브)'] / LOVE DIVE
6위 FOREVER 1 / ["소녀시대 (GIRLS' GENERATION)"] / FOREVER 1 - The 7th Album
7위 그때 그 순간 그대로 (그그그) / ['WSG워너비 (가야G)'] / WSG워너비 1집
8위 Cookie / ['NewJeans'] / NewJeans 1st EP 'New Jeans'
9위 새삥 (Prod. ZICO) (Feat. 호미들) / ['지코 (ZICO)'] / 스트릿 맨 파이터(SMF) Original Vol.3 (계급미션)
10위 보고싶었어 / ['WSG워너비 (4FIRE)'] / WSG워너비 1집
11위 사랑은 늘 도망가 / ['임영웅'] / 신사와 아가씨 OST Part.2
12위 SNEAKERS / ['ITZY (있지)'] / CHECKMATE
13위 그라데이션 / ['10CM'] / 5.3
14위 우리들의 블루스 / ['임영웅'] / IM HERO
15위 TOMBOY / ['(여자)아이들'] / I NEVER DIE
16위 정이라고 하자 (Feat. 10CM) / ['BIG Naughty (서동현)'] / 정이라고 하자
17위 POP! / ['나연 (TWICE)'] / IM NAYEON
18위 사랑인가 봐 / ['멜로망스'] / 사랑인가 봐 (사내맞선 OST 스페셜 트랙)
19위 나의 X에게 / ['경서'] / 나의 X에게
20위 다시 만날 수 있을까 / ['임영웅'] / IM HERO
21위 도깨비불 (Illusion) / ['aespa'] / Girls - The 2nd Mini Album
22위 That That (prod. & feat. SUGA of BTS) / ['싸이 (PSY)'] / 싸다9
23위 내가 아니라도 / ['주호'] / 내가 아니라도
24위 ELEVEN / ['IVE (아이브)'] / ELEVEN
25위 이제 나만 믿어요 / ['임영웅'] / 내일은 미스터트롯 우승자 특전곡
26위 무지개 / ['임영웅'] / IM HERO
27위 FEARLESS / ['LE SSERAFIM (르세라핌)'] / FEARLESS
28위 내 기쁨은 너가 벤틀리를 끄는 거야 / ['김승민'] / PROTOTYPE RESEARCH #0063
29위 해요 (2022) / ['#안녕'] / 해요 (2022)
30위 아버지 / ['임영웅'] / IM HERO
31위 Talk that Talk / ['TWICE (트와이스)'] / BETWEEN 1&2
32위 Love story / ['볼빨간사춘기'] / Seoul
33위 Girls / ['aespa'] / Girls - The 2nd Mini Album
34위 LAW (Prod. Czaer) / ['윤미래', '비비 (BIBI)'] / 스트릿 맨 파이터(SMF) Original Vol.3 (계급미션)
35위 A bientot / ['임영웅'] / IM HERO
36위 LOVE me / ["BE'O (비오)"] / LOVE me
37위 손이 참 곱던 그대 / ['임영웅'] / IM HERO
38위 사랑해 진짜 / ['임영웅'] / IM HERO
39위 인생찬가 / ['임영웅'] / IM HERO
40위 취중고백 / ['김민석 (멜로망스)'] / 취중고백
41위 사랑한다고 말해줘 / ['탑현'] / 사랑한다고 말해줘
42위 통화연결음 / ['보라미유', 'MJ (써니사이드)'] / 통화연결음
43위 That's Hilarious / ['Charlie Puth'] / Smells Like Me
44위 봄여름가을겨울 (Still Life) / ['BIGBANG (빅뱅)'] / 봄여름가을겨울 (Still Life)
45위 연애편지 / ['임영웅'] / IM HERO
46위 너의 모든 순간 / ['성시경'] / 별에서 온 그대 OST Part.7
47위 다정히 내 이름을 부르면 / ['경서예지', '전건호'] / 다정히 내 이름을 부르면 (경서예지 x 전건호)
48위 사랑역 / ['임영웅'] / IM HERO
49위 보금자리 / ['임영웅'] / IM HERO
50위 사랑해요 그대를 / ['임영웅'] / IM HERO

실습

In [122]:
res = req.get("http://www.naver.com")
soup = bs(res.text, "html.parser")

soup_naver = soup.select("a.nav")
for soup_naver_element in soup_naver:
    print(soup_naver_element.text)

메일
카페
블로그
지식iN
쇼핑
쇼핑LIVE
Pay
TV
사전
뉴스
증권
부동산
지도
VIBE
도서
웹툰

In [123]:
res = req.get("https://finance.naver.com/sise/sise_quant.naver")
soup = bs(res.text, "html.parser")

sotck_name_list = soup.select("a.tltle")

num = 0
stock_list = []
for sotck_name in sotck_name_list:
    num += 1
    stock_list.append(sotck_name.text)
    print(f"{num}위 : {sotck_name.text}")

1위 : KODEX 200선물인버스2X
2위 : 삼성 인버스 2X WTI원유 선물 ETN
3위 : KODEX 인버스
4위 : KODEX 코스닥150선물인버스
5위 : KODEX 레버리지
6위 : 삼성전자
7위 : 신한 인버스 2X 천연가스 선물 ETN
8위 : KODEX 코스닥150레버리지
9위 : 금양
10위 : 세원이앤씨
11위 : 신한 인버스 2X 천연가스 선물 ETN(H)
12위 : 신한 인버스 2X WTI원유 선물 ETN(H)
13위 : 대창
14위 : 대한전선
15위 : HLB글로벌
16위 : 현대로템
17위 : 혜인
18위 : 팬오션
19위 : TRUE 인버스 2X 천연가스 선물 ETN(H)
20위 : 에스엠벡셀
21위 : 신성이엔지
22위 : 두산에너빌리티
23위 : 한국항공우주
24위 : 한화솔루션
25위 : 조일알미늄
26위 : 쌍방울
27위 : 이수화학
28위 : 동국제강
29위 : 대원화성
30위 : KODEX 200
31위 : HMM
32위 : 동양
33위 : 한화에어로스페이스
34위 : 코스모화학
35위 : TIGER 200선물인버스2X
36위 : 다스코
37위 : SK하이닉스
38위 : 삼성 레버리지 WTI원유 선물 ETN
39위 : 카카오뱅크
40위 : TIGER 차이나전기차SOLACTIVE
41위 : TIGER 원유선물인버스(H)
42위 : 삼성중공업
43위 : 우리금융지주
44위 : 하이스틸
45위 : 수산중공업
46위 : 한화생명
47위 : 현대제철
48위 : KODEX 코스닥150
49위 : QV 인버스 레버리지 WTI원유 선물 ETN(H)
50위 : KODEX WTI원유선물인버스(H)
51위 : 이스타코
52위 : 에이프로젠
53위 : KEC
54위 : KODEX 2차전지산업
55위 : 카카오
56위 : KODEX 미국나스닥100레버리지(합성 H)
57위 : 미래아이앤지
58위 : 베트남개발1
59위 : 한미글로벌
60위 : 현대두산인프라코어
61위 : 이구산업
62위 : BNK금융지주
63위 : 하나금융지주
64위 : 제이알글로벌리츠
65위 : 후성
66위 : 대한해운
67위 : 삼부토건
68위 : KG스틸
69위 : 대우건설
70위 : 삼성엔지니어링
71위 : 신한지주
72위 : TYM
73위 : SH에너지화학
74위 : KODEX 미국달러선물인버스2X
75위 : 한창
76위 : GS글로벌
77위 : 대한항공
78위 : TIGER 단기통안채
79위 : KB금융
80위 : 신한 레버리지 WTI원유 선물 ETN(H)
81위 : TRUE 인버스 2X 나스닥 100 ETN
82위 : TIGER 미국필라델피아반도체나스닥
83위 : 신원
84위 : 기아
85위 : 사조동아원
86위 : 휴스틸
87위 : NI스틸
88위 : 도화엔지니어링
89위 : TIGER 미국S&P500
90위 : TIGER 인버스
91위 : 진원생명과학
92위 : 미래에셋증권
93위 : 서울식품
94위 : 보령
95위 : 삼성전자우
96위 : 제주은행
97위 : 포스코케미칼
98위 : 동양철관
99위 : 기업은행
100위 : LG디스플레이

In [124]:
stock_price_selector = soup.select("td.number")
stock_price_text = []
for i in stock_price_selector:
    stock_price_text.append(i.text)

num = 0
stock_price_list = []
while num < 1000:
    stock_price_list.append(stock_price_text[num])
    num+=10

for x in range(100):
    stock_name = stock_list[x]
    stock_price = stock_price_text[x]
    print(f"{x+1}위 {stock_name} - 현재가 : {stock_price}")

1위 KODEX 200선물인버스2X - 현재가 : 3,050
2위 삼성 인버스 2X WTI원유 선물 ETN - 현재가 :

				205


3위 KODEX 인버스 - 현재가 :

				-6.30%


4위 KODEX 코스닥150선물인버스 - 현재가 : 183,288,144
5위 KODEX 레버리지 - 현재가 : 565,459
6위 삼성전자 - 현재가 : 3,050
7위 신한 인버스 2X 천연가스 선물 ETN - 현재가 : 3,055
8위 KODEX 코스닥150레버리지 - 현재가 : 20,469
9위 금양 - 현재가 : N/A
10위 세원이앤씨 - 현재가 : N/A
11위 신한 인버스 2X 천연가스 선물 ETN(H) - 현재가 : 140
12위 신한 인버스 2X WTI원유 선물 ETN(H) - 현재가 :

				15


13위 대창 - 현재가 :

				-9.68%


14위 대한전선 - 현재가 : 42,673,782
15위 HLB글로벌 - 현재가 : 5,977
16위 현대로템 - 현재가 : 135
17위 혜인 - 현재가 : 140
18위 팬오션 - 현재가 : 2,096
19위 TRUE 인버스 2X 천연가스 선물 ETN(H) - 현재가 : N/A
20위 에스엠벡셀 - 현재가 : N/A
21위 신성이엔지 - 현재가 : 4,830
22위 두산에너빌리티 - 현재가 :

				155


23위 한국항공우주 - 현재가 :

				-3.11%


24위 한화솔루션 - 현재가 : 27,869,304
25위 조일알미늄 - 현재가 : 135,229
26위 쌍방울 - 현재가 : 4,830
27위 이수화학 - 현재가 : 4,835
28위 동국제강 - 현재가 : 8,588
29위 대원화성 - 현재가 : N/A
30위 KODEX 200 - 현재가 : N/A
31위 HMM - 현재가 : 4,835
32위 동양 - 현재가 :

				145


33위 한화에어로스페이스 - 현재가 :

				-2.91%


34위 코스모화학 - 현재가 : 27,372,542
35위 TIGER 200선물인버스2X - 현재가 : 132,560
36위 다스코 - 현재가 : 4,835
37위 SK하이닉스 - 현재가 : 4,840
38위 삼성 레버리지 WTI원유 선물 ETN - 현재가 : 4,646
39위 카카오뱅크 - 현재가 : N/A
40위 TIGER 차이나전기차SOLACTIVE - 현재가 : N/A
41위 TIGER 원유선물인버스(H) - 현재가 : 15,170
42위 삼성중공업 - 현재가 :

				890


43위 우리금융지주 - 현재가 :

				+6.23%


44위 하이스틸 - 현재가 : 23,807,260
45위 수산중공업 - 현재가 : 357,420
46위 한화생명 - 현재가 : 15,170
47위 현대제철 - 현재가 : 15,175
48위 KODEX 코스닥150 - 현재가 : 21,837
49위 QV 인버스 레버리지 WTI원유 선물 ETN(H) - 현재가 : N/A
50위 KODEX WTI원유선물인버스(H) - 현재가 : N/A
51위 이스타코 - 현재가 : 58,100
52위 에이프로젠 - 현재가 :

				2,500


53위 KEC - 현재가 :

				+4.50%


54위 KODEX 2차전지산업 - 현재가 : 16,900,786
55위 카카오 - 현재가 : 975,810
56위 KODEX 미국나스닥100레버리지(합성 H) - 현재가 : 58,100
57위 미래아이앤지 - 현재가 : 58,200
58위 베트남개발1 - 현재가 : 3,468,444
59위 한미글로벌 - 현재가 : 8.81
60위 현대두산인프라코어 - 현재가 : 13.92
61위 이구산업 - 현재가 : 165
62위 BNK금융지주 - 현재가 :

				25


63위 하나금융지주 - 현재가 :

				-13.16%


64위 제이알글로벌리츠 - 현재가 : 14,117,226
65위 후성 - 현재가 : 2,312
66위 대한해운 - 현재가 : 160
67위 삼부토건 - 현재가 : 165
68위 KG스틸 - 현재가 : 569
69위 대우건설 - 현재가 : N/A
70위 삼성엔지니어링 - 현재가 : N/A
71위 신한지주 - 현재가 : 8,860
72위 TYM - 현재가 :

				500


73위 SH에너지화학 - 현재가 :

				+5.98%


74위 KODEX 미국달러선물인버스2X - 현재가 : 13,127,472
75위 한창 - 현재가 : 116,122
76위 GS글로벌 - 현재가 : 8,860
77위 대한항공 - 현재가 : 8,865
78위 TIGER 단기통안채 - 현재가 : 9,073
79위 KB금융 - 현재가 : N/A
80위 신한 레버리지 WTI원유 선물 ETN(H) - 현재가 : N/A
81위 TRUE 인버스 2X 나스닥 100 ETN - 현재가 : 17,700
82위 TIGER 미국필라델피아반도체나스닥 - 현재가 :

				250


83위 신원 - 현재가 :

				+1.43%


84위 기아 - 현재가 : 11,584,688
85위 사조동아원 - 현재가 : 197,834
86위 휴스틸 - 현재가 : 17,650
87위 NI스틸 - 현재가 : 17,700
88위 도화엔지니어링 - 현재가 : 10,192
89위 TIGER 미국S&P500 - 현재가 : 57.10
90위 TIGER 인버스 - 현재가 : 13.57
91위 진원생명과학 - 현재가 : 796
92위 미래에셋증권 - 현재가 :

				22


93위 서울식품 - 현재가 :

				+2.84%


94위 보령 - 현재가 : 10,801,665
95위 삼성전자우 - 현재가 : 8,658
96위 제주은행 - 현재가 : 795
97위 포스코케미칼 - 현재가 : 796
98위 동양철관 - 현재가 : 1,413
99위 기업은행 - 현재가 : -13.49
100위 LG디스플레이 - 현재가 : -1.44

In [125]:
import pandas as pd

In [126]:
print(len(stock_price_list)) 
print(len(stock_list))

100
100

In [127]:
data = {"종목명" : stock_list, "현재가" : stock_price_list}
kospi = pd.DataFrame(data)
kospi

                       종목명      현재가
0         KODEX 200선물인버스2X    3,050
1   삼성 인버스 2X WTI원유 선물 ETN      140
2                KODEX 인버스    4,830
3        KODEX 코스닥150선물인버스    4,835
4               KODEX 레버리지   15,170
..                     ...      ...
95                    제주은행    6,810
96                  포스코케미칼  179,500
97                    동양철관    1,135
98                    기업은행    9,710
99                 LG디스플레이   15,800

[100 rows x 2 columns]

In [128]:
# kospi.to_excel("코스피지수.xlsx", encoding = "utf-8")/

In [129]:
header = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'}
 
url = "https://music.bugs.co.kr/chart"
res = req.get(url, headers=header).text
# get함수로 raw데이터 가져오기
soup = bs(res, "lxml")

song_rank_select = soup.select("div.ranking > strong")
song_name_select = soup.select("p.title > a")
artist_name_select = soup.select("p.artist > a")
artist_name_select2 = soup.select("p.artist > a")
album_name_select = soup.select("td.left > a")

song_rank_list = []
song_name_list = []
artist_name_list = []
album_name_list = []
for x in range(100):
    song_rank_list.append(song_rank_select[x].text)
    song_name_list.append(song_name_select[x].text)
    artist_name_list.append(artist_name_select[x].text)
    album_name_list.append(album_name_select[x].text)

In [130]:
artist_name_check = soup.select("a.more")
len(artist_name_check)

9

In [131]:
for i in artist_name_check:
    artist_name_select.remove(i)

In [132]:
artist_name_test = []
for x in range(100):
    artist_name_test.append(artist_name_select[x].text)

In [145]:
data = {"순위" : song_rank_list, "곡" : song_name_list,  "아티스트" : artist_name_test, "앨범" : album_name_list}
songs_rank = pd.DataFrame(data)
songs_rank.set_index("순위")

,곡,아티스트,앨범
순위,,,
1,Hype Boy,NewJeans,NewJeans 1st EP 'New Jeans'
2,After LIKE,IVE (아이브),After LIKE
3,Attention,NewJeans,NewJeans 1st EP 'New Jeans'
4,새삥 (Prod. ZICO) (Feat. 호미들),지코,스트릿 맨 파이터(SMF) Original Vol.3 (계급미션)
5,Pink Venom,BLACKPINK,Pink Venom
...,...,...,...
96,Jiggle Jiggle,Duke & Jones(듀크 존스),Jiggle Jiggle
97,새들처럼,멜로망스(MeloMance),PLAYLIST (플레이리스트) OST Part.1
98,되돌리다,이승기,숲
99,그때 그 시절,XIA(준수),그때 그 시절 (웹툰 '굿닥터' X XIA (준수))
100,Weekend,태연 (TAEYEON),Weekend

In [134]:
artist_name_check2 = soup.select("a.artistTitle")
for i in artist_name_check2:
    artist_name_select2.remove(i)

In [135]:
artist_name_list2 = []
for i in artist_name_select2:
    artist_name_list2.append(i.text)
artist_name_list2

for i in artist_name_list2:
    if "\n" or "\r" in i:
        i.replace("\r\n","")
    else:
        pass

In [136]:
artist_name_list2

['NewJeans',
 'IVE (아이브)',
 'NewJeans',
 '지코',
 'BLACKPINK',
 '\r\n지아(Zia)\r\n',
 '\r\n윤미래\r\n',
 'IVE (아이브)',
 "소녀시대 (GIRLS' GENERATION)",
 'NewJeans',
 '멜로망스(MeloMance)',
 'TWICE (트와이스)',
 '원어스 (ONEUS)',
 'ITZY (있지)',
 '원어스 (ONEUS)',
 'BIG Naughty (서동현)',
 'WSG워너비 (가야G)',
 'Charlie Puth(찰리 푸스)',
 '멜로망스(MeloMance)',
 '윤하(Younha/ユンナ)',
 'IVE (아이브)',
 '원어스 (ONEUS)',
 'aespa',
 'LE SSERAFIM (르세라핌)',
 '임영웅',
 '지코',
 '10CM',
 '(여자)아이들',
 '한동근',
 '경서',
 'OneRepublic(원리퍼블릭)',
 'WSG워너비 (4FIRE)',
 '나연 (TWICE)',
 'Charlie Puth(찰리 푸스)',
 'WSG워너비',
 '원어스 (ONEUS)',
 '김승민',
 '\r\n경서예지\r\n',
 '\r\n로꼬\r\n',
 'aespa',
 '츄 (이달의 소녀)',
 '원어스 (ONEUS)',
 'NewJeans',
 '원어스 (ONEUS)',
 'BIGBANG (빅뱅)',
 '\r\nThe Kid LAROI\r\n',
 'WINNER',
 '선미',
 '원어스 (ONEUS)',
 '(여자)아이들',
 '\r\nCharlie Puth(찰리 푸스)\r\n',
 '싸이 (PSY)',
 '펀치 (Punch)',
 '다비치',
 'Harry Styles(해리 스타일스)',
 "BE'O (비오)",
 '태연 (TAEYEON)',
 '김민석 (멜로망스)',
 'YENA (최예나)',
 'STAYC(스테이씨)',
 '아이유(IU)',
 '21학번',
 'BIG Naughty (서동현)',
 'Justin Bieber(저스틴 비버)',
 'YENA (최예나)',
 '볼빨간사춘기',
 '\r\n보라미유\r\n',
 'Red Velvet (레드벨벳)',
 '성시경',
 '이무진',
 '투앤비(2NB)',
 '주호',
 '아이유(IU)',
 '#안녕',
 '\r\n우원재\r\n',
 'aespa',
 '백예린 (Yerin Baek)',
 '폴킴(Paul Kim)',
 '마마무+',
 '케이시',
 '폴킴(Paul Kim)',
 '지코',
 '박재범',
 '정기고(Junggigo)',
 'MSG워너비(M.O.M)',
 '케이시',
 '기리보이',
 '청하',
 '다비치',
 '2am',
 '임창정',
 '탑현',
 '백예린 (Yerin Baek)',
 '휘인(Whee In)',
 '임창정',
 '\r\nDuke & Jones(듀크 존스)\r\n',
 '멜로망스(MeloMance)',
 '이승기',
 'XIA(준수)',
 '태연 (TAEYEON)']

In [137]:
header = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'}
 
url = "https://movie.naver.com/movie/point/af/list.naver"
res = req.get(url, headers=header).text
# get함수로 raw데이터 가져오기
soup = bs(res, "lxml")

movie_name_select = soup.select("td.title > a.movie.color_b")
movie_score_select = soup.select("div.list_netizen_score > em")
movie_review_select = soup.select("td.title")

movie_score_list = []
movie_name_list = []
for i in movie_score_select:
    movie_score_list.append(i.text)
for i in movie_name_select:
    movie_name_list.append(i.text)

In [138]:
movie_review_final = []
for i in movie_review_select:
    a = i.text.split("\n\n")[2]
    a = a.replace("\n", "").replace("\t", "").replace("신고", "")
    movie_review_final.append(a)

movie_review_final

['영화관에서 보니까 국뽕 지리더라구요. 좋았습니다. ',
 '역시 김호중가수는 전세계가 알아주는 테너 맞네요 ',
 '가끔 가다 보이는 돈 모자란 CG말고는 나름 마블식 유머 잘 끼워넣었고. 영상미는 눈을 꽤 즐겁게 한다. 기대를 안하고 봐서인지 스토리도 나쁘지 않았다. PCPC 하길래 곰곰히 생각해보니 발키리랑 바위의 동성애. 굳이 필요한 내용이었나? 싶은 요소는 좀 별로지만. 괜찮은 결말, 고르의 열연은 여운을 남긴다 ',
 '와 진짜 화려한 배우 캐스팅 대비 많은 실망감이 남습니다.. ',
 '초보 감독이 이 정도면 준수하지요. ',
 '막판에 초글링 싸움에 토린이 데뷔전은 뭐냐 ',
 '이정재배우의 감독변신재밌는영화 ',
 '연기너무잘하시고너무웃김 재밌음  맘편안히 웃고오세요 ',
 '마지막에 산에서 싸우려고 스토리가 산으로 가는거였구나.. ',
 '액션도 너무 좋고 재미있었습니다 ']

In [139]:
len(movie_review_final), len(movie_score_list), len(movie_name_list)

(10, 10, 10)

# 10페이지까지 크롤링

In [140]:
page = range(1, 11) 

total_score_list = []
total_title_list = []    
total_review_list = []

for i in tqdm(page):
    url = f"https://movie.naver.com/movie/point/af/list.naver?page{i}"
    
    movie_name_select = soup.select("td.title > a.movie.color_b")
    movie_score_select = soup.select("div.list_netizen_score > em")
    movie_review_select = soup.select("td.title")

    
    for i in movie_score_select:
        total_score_list.append(i.text)
    for i in movie_name_select:
        total_title_list.append(i.text)


    for i in movie_review_select:
        a = i.text.split("\n\n")[2]
        a = a.replace("\n", "").replace("\t", "").replace("신고", "")
        total_review_list.append(a)

C:\Users\user\AppData\Local\Temp\ipykernel_10424\623736275.py:7: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for i in tqdm(page):

  0%|          | 0/10 [00:00<?, ?it/s]

In [143]:
data = {"영화" : total_title_list, "평점" : total_score_list,  "리뷰" : total_review_list}
movie_rank = pd.DataFrame(data)
movie_rank

               영화  평점                                                 리뷰
0       한산: 용의 출현  10                       영화관에서 보니까 국뽕 지리더라구요. 좋았습니다.
1   인생은 뷰티풀: 비타돌체  10                        역시 김호중가수는 전세계가 알아주는 테너 맞네요
2     토르: 러브 앤 썬더   8  가끔 가다 보이는 돈 모자란 CG말고는 나름 마블식 유머 잘 끼워넣었고. 영상미는 ...
3           서울대작전   4                 와 진짜 화려한 배우 캐스팅 대비 많은 실망감이 남습니다..
4              헌트   8                               초보 감독이 이 정도면 준수하지요.
..            ...  ..                                                ...
95    토르: 러브 앤 썬더   1                           막판에 초글링 싸움에 토린이 데뷔전은 뭐냐
96             헌트  10                                  이정재배우의 감독변신재밌는영화
97      육사오(6/45)  10                      연기너무잘하시고너무웃김 재밌음  맘편안히 웃고오세요
98            리미트   3                   마지막에 산에서 싸우려고 스토리가 산으로 가는거였구나..
99     공조2: 인터내셔날  10                                 액션도 너무 좋고 재미있었습니다

[100 rows x 3 columns]